version: '3.1'
services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: my-events
  event-backend:
    links:
      - db:event-db
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    command: npm run start:sql
